// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awrmhoxdvaoyaxcmgcoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3cm1ob3hkdmFveWF4Y21nY296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2NDQ5ODQsImV4cCI6MjA5MDIyMDk4NH0.XrcCS-Lm6gIQ11RD4_KhztPUeeRY3cJ8jdQMlNieq7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});